# Generated by Django 5.1.1 on 2024-10-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("control_panel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConnectedClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_id", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("ip_address", models.GenericIPAddressField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("connected", "Connected"),
                            ("disconnected", "Disconnected"),
                        ],
                        default="connected",
                        max_length=50,
                    ),
                ),
                ("last_seen", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
