# Generated by Django 5.1.1 on 2024-10-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("control_panel", "0002_connectedclient"),
    ]

    operations = [
        migrations.AddField(
            model_name="connectedclient",
            name="last_domain_accessed",
            field=models.CharField(default="www.google.com", max_length=255),
        ),
    ]
