# Generated by Django 5.1.1 on 2024-10-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("control_panel", "0003_connectedclient_last_domain_accessed"),
    ]

    operations = [
        migrations.AddField(
            model_name="connectedclient",
            name="OS",
            field=models.CharField(default="unknown", max_length=255),
        ),
        migrations.AddField(
            model_name="connectedclient",
            name="systemname",
            field=models.CharField(default="unknown", max_length=255),
        ),
    ]
